Getting ready

diff --git a/initramfs_skeleton/init b/initramfs_skeleton/init
--- a/initramfs_skeleton/init
+++ b/initramfs_skeleton/init
@@ -45,102 +45,10 @@ function msg_nonewline() {
 	echo -n "$message" >> /tmp/initramfs_serial.log
 }
 
-function detect_chip_and_fw() {
-# Description: Detect chip family and current firmware to run later operations correctly
-	chip_name=$(ipcinfo-mips32 --chip-name)
-	chip_family=$(ipcinfo-mips32 --family)
-	msg "Detected chip name: $chip_name, chip family: $chip_family"
-
-	dd if=/dev/mtd0 of=/boot_backup.img
-	strings /boot_backup.img > /boot_backup_strings.txt
-
-	if grep -q "demo.bin" /boot_backup_strings.txt ; then # Cam v2 & Cam Pan
-		msg "Camera is currently on Cam Pan v2 or Cam Pan stock firmware"
-		current_fw="stock"
-	
-	elif grep -q "demo_wcv3.bin" /boot_backup_strings.txt ; then # Cam v3
-		msg "Camera is currently on Cam v3 stock firmware"
-		current_fw="stock"
-	
-	elif grep -q "recovery_wcpv2.bin" /boot_backup_strings.txt ; then # Cam Pan v2
-		msg "Camera is currently on Cam Pan v2 stock firmware"
-		current_fw="stock"
-	
-	elif grep -q "factory_0P3N1PC_kernel" /boot_backup_strings.txt ; then
-		msg "Camera is currently on OpenIPC firmware"
-		current_fw="openipc"
-	
-	else
-		msg "Unable to detect current firmware"
-	
-	fi
-
-	rm /boot_backup_strings.txt
-}
-
-function import_functions_and_variables() {
-# Description: Set needed files and paths variables for this program, source functions for later operations and set extra variables based on detected current system info
-	prog_name="wz_flash-helper"
-	prog_version=$(cat /prog_ver.txt)
-	
-	prog_dir="/sdcard/wz_flash-helper"
-	
-	prog_config_file="/sdcard/wz_flash-helper/wz_flash-helper.conf"
-	prog_log_file="/sdcard/wz_flash-helper/wz_flash-helper.log"
-	prog_log_file_serial="/sdcard/wz_flash-helper/wz_flash-helper_serial.log"
-	
-	concat_partmtd="/dev/mtd21"
-	
-	source /functions_io.sh
-	source /variables_init_msg.sh
-	source /funcs_and_vars_openipc.sh
-	
-	case "$chip_family" in
-		"t20")
-			source /funcs_and_vars_t20_stock.sh ;;
-		"t31")
-			source /funcs_and_vars_t31_stock.sh ;;
-	esac
-
-	if [[ "$current_fw" == "stock" ]] && [[ "$chip_family" == "t20" ]]; then
-		sdcard_boot_img_name="factory_ZMC6tiIDQN"
-		
-	elif [[ "$current_fw" == "stock" ]] && [[ "$chip_family" == "t31" ]]; then
-		sdcard_boot_img_name="factory_t31_ZMC6tiIDQN"
-	
-	elif [[ "$current_fw" == "openipc" ]]; then
-		sdcard_boot_img_name="factory_0P3N1PC_kernel"
-	
-	fi
-}
-
-function initialize_gpio() {
-# Description: Initialize GPIO for LEDs and SD card on T20 camera
-	msg "Exporting GPIO pins for LEDs"
-	if [ ! -d /sys/class/gpio/gpio38 ]; then # Export LEDs GPIO pins if they don't exist to enable LEDs
-		echo 38 > /sys/class/gpio/export
-		echo out > /sys/class/gpio/gpio38/direction
-		echo 1 > /sys/class/gpio/gpio38/value
-	fi
-	
-	if [ ! -d /sys/class/gpio/gpio39 ]; then
-		echo 39 > /sys/class/gpio/export
-		echo out > /sys/class/gpio/gpio39/direction
-		echo 1 > /sys/class/gpio/gpio39/value
-	fi
-
-	if [[ "$chip_family" == "t20" ]]; then # T20 camera need this to get SD card detected
-		msg "Exporting GPIO pin to detect SD card on T20 camera"
-		echo 43 > /sys/class/gpio/export
-		echo in > /sys/class/gpio/gpio43/direction
-		sleep 3 # Required delay interval for SD card init on T20 camera
-	fi
-}
-
 function welcome_msg() {
 # Description: It is nice to let the user know that they are welcome!
 	msg
-	msg "Welcome to $prog_name init $prog_version!"
+	msg "Welcome to initramfs init!"
 	msg
 }
 
@@ -169,41 +77,30 @@ function mount_sdcard() {
 	mount -t vfat /dev/mmcblk0p1 /sdcard -o rw,umask=0000,dmask=0000 && msg "succeeded" || msg "failed"
 }
 
+function import_config_file() {
+# Description: Source program config file to know and do what the user wants
+	[ ! -d $prog_dir ] && { msg "$prog_dir does not exist. Creating it to store log files. Nothing will be done" ; mkdir -p $prog_dir ; return 1 ; }
+	[ ! -f $prog_config_file ] && { msg "$prog_config_file file is missing. Nothing will be done" ; return 1 ; }
+
+	# Fix issue that config file failed to be sourced if it contains MS-DOS newline
+	dos2unix $prog_config_file && source $prog_config_file || { msg "$prog_config_file file is invalid. Nothing will be done" ; return 1 ; }
+}
+
 function rename_prog_sdcard_boot_img() {
+# Description: Rename SD card boot image to avoid infinite boot loop
 	msg "Renaming /sdcard/$sdcard_boot_img_name to /sdcard/$sdcard_boot_img_name.$prog_name"
 	mv /sdcard/$sdcard_boot_img_name /sdcard/$sdcard_boot_img_name.$prog_name
 }
 
-function import_config_file() {
-# Description: Source program config file to know and do what the user wants
-	[ ! -d $prog_dir ] && { msg "$prog_dir does not exist. Creating it to store log files. Nothing will be done" ; mkdir -p $prog_dir ; exit_init ; }
-	[ ! -f $prog_config_file ] && { msg "$prog_config_file file is missing. Nothing will be done" ; exit_init ; }
-
-	# Fix issue that config file failed to be sourced if it contains MS-DOS newline
-	dos2unix $prog_config_file && source $prog_config_file || { msg "$prog_config_file file is invalid. Nothing will be done" ; exit_init ; }
-}
-
-function emulate_chip_family_and_fw () {
-# Description: Emulate chip family and firmware for testing, only!
-	dry_run="yes" # Override config file option so nothing is actually done
-
-	chip_family="t20"
-	current_fw="openipc"
+function display_info() {
 	msg
-	msg "### Emulation mode: chip_family: $chip_family, current_fw: $current_fw"	
-	msg "### Dry run mode is forcibly Enabled. No modification will be made."
+	msg "Program version: $prog_version"
+	msg "Hardware: $chip_name, chip family: $chip_family, flash type: $flash_type"
+	msg "Current firmware profile: $current_profile_profile"
 	msg
-
-	case "$chip_family" in # Source device-dependent script in case it has not been sourced
-		"t20")
-			source /funcs_and_vars_t20_stock.sh ;;
-		"t31")
-			source /funcs_and_vars_t31_stock.sh ;;
-	esac
 }
 
 function exit_init() {
-# Description: Rename SD card boot image to avoid infinite boot loop
 	msg
 	msg "---------- Exit init ----------"
 	msg
@@ -218,25 +115,32 @@ function exit_init() {
 
 	sleep 1
 	exit # Crash init to reboot immediately
-	sleep 10 # This prevents init from continuing after exit_init is finished but the camera has not rebooted immediately
+	sleep 10 # Prevents init from continuing after exit_init is finished but the camera has not rebooted immediately
 }
 
 function main() {
-	detect_chip_and_fw
-	import_functions_and_variables
-	initialize_gpio
-
+	source /prepare_detect.sh || return 1
+	source /prepare_get_prog_info.sh
+	source /prepare_init_msg.sh
+	source /functions_io.sh
+	
+	source /prepare_initialize_gpio.sh
+	
 	welcome_msg
 	
 	wait_init_interrupt
 	
-	mount_sdcard
+	mount_sdcard || return 1
+	
+	import_config_file || return 1
+	
+	source /prepare_emulate.sh
+	source /prepare_import.sh || return 1
+
 	rename_prog_sdcard_boot_img
 	
-	import_config_file
-
-	emulate_chip_family_and_fw
-
+	display_info
+	
 	[[ "$dry_run" == "yes" ]] && msg "$dry_run_yes" || msg "$dry_run_no"
 
 	#---------- Backup operation ----------
@@ -255,12 +159,12 @@ function main() {
 		msg "$restore_partitions_no"
 	fi
 
-	#---------- Switch fw operation ----------
-	if [[ "$switch_fw" == "yes" ]]; then
-		msg "$switch_fw_yes"
-		source /operation_switch_fw.sh && msg "$switch_fw_succeed" || { msg "$switch_fw_fail" ; return 1 ; }
+	#---------- Switch profile operation ----------
+	if [[ "$switch_profile" == "yes" ]]; then
+		msg "$switch_profile_yes"
+		source /operation_switch_profile.sh && msg "$switch_profile_succeed" || { msg "$switch_profile_fail" ; return 1 ; }
 	else
-		msg "$switch_fw_no"
+		msg "$switch_profile_no"
 	fi
 
 	#---------- Custom script ----------
@@ -274,7 +178,7 @@ function main() {
 	#---------- Continue boot image ----------
 	if [[ "$enable_continue_boot_img" == "yes" ]]; then
 		msg "$enable_continue_boot_img_yes"
-		source /action_move_continue_boot_img_file.sh && msg "$enable_continue_boot_img_succeed" || { msg "$enable_continue_boot_img_fail" ; return 1 ; }
+		source /action_copy_continue_boot_img_file.sh && msg "$enable_continue_boot_img_succeed" || { msg "$enable_continue_boot_img_fail" ; return 1 ; }
 	else
 		msg "$enable_continue_boot_img_no"
 	fi
