Improve wordings and code

diff --git a/initramfs_root/init b/initramfs_root/init
--- a/initramfs_root/init
+++ b/initramfs_root/init
@@ -10,7 +10,8 @@
 
 mkdir -p /dev /proc /sys /tmp
 mkdir -p /mnt /var/lock
-
+mkdir -p /sdcard
+	
 exec > /tmp/initramfs.log 2>&1 # Comment out this line to debug with serial connection
 set -x
 
@@ -48,7 +49,7 @@ function msg_nonewline() {
 }
 
 function play_audio() {
-# Description: Play audio to inform users the progress who don't have serial connection
+# Description: Play audio to let the user keep track of the progress, useful when they don't have serial connection
 	[[ ! "$enable_audio" == "yes" ]] && return 0
 
 	audio_title="$1"
@@ -71,7 +72,7 @@ function play_audio() {
 	esac
 	
 	local numberic='^[0-9]+$'
-	if [[ ! "$audio_volume" =~ $numberic ]] || [[ "$audio_volume" == "" ]] || [ "$audio_volume" -lt 0 ] || [ "$audio_volume" -gt 100 ]; then
+	if [[ ! "$audio_volume" =~ $numberic ]] || [[ "$audio_volume" == "" ]] || [ "$audio_volume" -lt 0 ] || [ "$audio_volume" -gt 100 ]; then # Check for invalid audio value
 		local audio_volume="50"
 	fi
 	audioplay $audio_file $audio_volume
@@ -90,13 +91,13 @@ function import_init_msg() {
 }
 
 function import_functions_io() {
-# Description: Import script which contains functions to read/write on flash chip
+# Description: Import the "io" script which contains functions to read/write partitions
 	source /functions_io.sh
 }
 
 function load_kernel_modules() {
-# Description: Load kernel modules for device chip family
-	if ls /kernel_module.d/model_speciality.d/*.sh ; then
+# Description: Load kernel modules for camera chip family
+	if ls /kernel_module.d/model_speciality.d/*.sh ; then # Some camera models need to load kernel modules with parameters
 		for speciality_kmod_script in /kernel_module.d/model_speciality.d/*.sh ; do
 			source $speciality_kmod_script
 		done
@@ -119,7 +120,7 @@ function welcome() {
 # Description: It is nice to let the user know that they are welcome!
 	msg
 	msg
-	msg "Welcome to initramfs init! ^_^"
+	msg "Welcome to initramfs init! ^_^" # Yep, a smiling emoji!
 	msg
 }
 
@@ -128,23 +129,22 @@ function wait_init_interrupt() {
 	echo > /dev/console
 	echo "Press any key to interrupt init" > /dev/console
 	
-	exec 0< /dev/console
+	exec 0< /dev/console # Allow the user to type on serial terminal
 	read -r -s -n 1 -t 3
 	if [[ "$?" -eq 0 ]]; then
 		echo "Dropping a shell" > /dev/console
 		echo "You can run resize command to make terminal output match terminal size" > /dev/console
-		cd /
 		exec 1> /dev/console
 		exec 2> /dev/console
-		exec /bin/sh
+		cd / && exec /bin/sh
 	fi
 	echo "Action has timed out" > /dev/console
-	exec 0< /dev/null
 	echo > /dev/console
+	exec 0< /dev/null # Stop the user from typing on serial terminal
 }
 
 function backup_bootpart() {
-# Description: Create backup for boot partition to rollback in case it gets corrupted, and for profile detection
+# Description: Create backup for boot partition to rollback in case it gets corrupted, and to detect current profile by analyzing its strings
 	dd if=/dev/mtdblock0 of=/bootpart_backup.img status=none
 	strings /bootpart_backup.img > /bootpart_backup.img.strings
 }
@@ -155,7 +155,7 @@ function detect_current_profile() {
 }
 
 function import_prog_info() {
-# Description: Import basic program variables
+# Description: Import program variables
 	source /init_variables_prog_info.sh
 }
 
@@ -175,44 +175,44 @@ function mount_sdcard() {
 # Description: Mount SD card, nothing more
 	msg
 	msg_nonewline "Mounting SD card... "
-	mkdir -p /sdcard
 	mount -t vfat /dev/mmcblk0p1 /sdcard -o rw,umask=0000,dmask=0000 && msg "succeeded" || msg "failed"
 }
 
-function rename_prog_sdcard_kernelimg() {
-# Description: Rename program SD card boot image to avoid infinite boot loop
-	if [ -f /sdcard/$current_profile_sdcard_kernelimg_name ]; then
-		msg_nonewline "Renaming program kernel image on SD card: $current_profile_sdcard_kernelimg_name to $current_profile_sdcard_kernelimg_name.$prog_name... "
-		mv /sdcard/$current_profile_sdcard_kernelimg_name /sdcard/$current_profile_sdcard_kernelimg_name.$prog_name && { msg "succeeded" ; return 0 ; } || msg "failed"
+function rename_prog_sdcard_kernel() {
+# Description: Rename program SD card kernel to avoid infinite boot loop
+	if [ -f /sdcard/$current_profile_sdcard_kernel_name ]; then
+		msg_nonewline "Renaming program SD card kernel: $current_profile_sdcard_kernel_name to $current_profile_sdcard_kernel_name.$prog_name... "
+		mv /sdcard/$current_profile_sdcard_kernel_name /sdcard/$current_profile_sdcard_kernel_name.$prog_name && { msg "succeeded" ; return 0 ; } || msg "failed"
 	else
-		msg "Program SD card kernel image $current_profile_sdcard_kernelimg_name for this profile is missing"
+		msg "Program SD card kernel $current_profile_sdcard_kernel_name for this profile is missing"
 	fi
 
-	if [[ ! "$current_profile_sdcard_secondary_kernelimg_name" == "" ]] && [ -f /sdcard/$current_profile_sdcard_secondary_kernelimg_name ]; then
-		msg_nonewline "Renaming program secondary kernel image on SD card: $current_profile_sdcard_secondary_kernelimg_name to $current_profile_sdcard_secondary_kernelimg_name.$prog_name... "
-		mv /sdcard/$current_profile_sdcard_secondary_kernelimg_name /sdcard/$current_profile_sdcard_secondary_kernelimg_name.$prog_name && { msg "succeeded" ; return 0 ; } || msg "failed"
+	# OpenIPC uboot for Ingenic can load SD card kernel with two filenames, the second SD card kernel will be renamed if found to prevent bootloop
+	if [[ ! "$current_profile_sdcard_secondary_kernel_name" == "" ]] && [ -f /sdcard/$current_profile_sdcard_secondary_kernel_name ]; then
+		msg_nonewline "Renaming program secondary SD card kernel: $current_profile_sdcard_secondary_kernel_name to $current_profile_sdcard_secondary_kernel_name.$prog_name... "
+		mv /sdcard/$current_profile_sdcard_secondary_kernel_name /sdcard/$current_profile_sdcard_secondary_kernel_name.$prog_name && { msg "succeeded" ; return 0 ; } || msg "failed"
 	else
-		msg "Program SD card secondary kernel image $current_profile_sdcard_secondary_kernelimg_name for this profile is missing"
+		msg "Program SD card secondary kernel $current_profile_sdcard_secondary_kernel_name for this profile is missing"
 	fi
 	return 1
 }
 
 function import_prog_config_file() {
-# Description: Source program config files to know and do what the user wants
+# Description: Source program config file to know and do what the user wants
 	[ ! -d $prog_dir ] && { msg "$prog_dir does not exist. Creating it to store log files. Nothing will be done" ; mkdir -p $prog_dir ; return 1 ; }
 	[ ! -f $prog_config_file ] && { msg "$prog_config_file file is missing. Nothing will be done" ; return 1 ; }
 
-	# Fix issue that config file failed to be sourced if it contains MS-DOS newline
+	# Fix issue that config file fails to be sourced if it contains MS-DOS newlines
 	dos2unix $prog_config_file && source $prog_config_file || { msg "$prog_config_file file is invalid. Nothing will be done" ; return 1 ; }
 }
 
-function detect_device_model() {
-# Description: Detect current camera model by reading the factory generated file
+function detect_camera_model() {
+# Description: Detect current camera model by reading the factory generated config file
 	source /profile.d/$chip_family/$current_profile/detect_model.sh
 }
 
 function display_info() {
-# Description: Let user know system info and current status
+# Description: Display system info and current status
 	msg
 	msg "Program version: $(cat /prog_ver.txt)"
 	msg "Hardware: chip name: $chip_name, chip family: $chip_family, flash type: $flash_type, model: $model"
@@ -221,7 +221,7 @@ function display_info() {
 }
 
 function exit_init() {
-# Description: Copy log files to SD card and exit, user can still interupt it for debugging before it actually exits
+# Description: Copy log files to SD card and reboot, the user can still interrupt and access initramfs shell for debugging before the reboot
 	msg
 	msg "---------- Exit init ----------"
 	msg
@@ -241,7 +241,7 @@ function exit_init() {
 	umount -a -r
 	play_audio "rebooting"
 	reboot -f # Reboot immediately
-	sleep 10 # Prevents init from continuing after exit_init is finished but the camera has not rebooted immediately
+	sleep 10 # Prevent init from continuing after exit_init finishes but the camera has not rebooted immediately
 }
 
 function main() {
@@ -260,14 +260,15 @@ function main() {
 	
 	detect_current_profile || return 1
 	emulate
+	
 	import_current_profile || return 1
 	import_prog_info
 	
 	mount_sdcard || return 1
-	rename_prog_sdcard_kernelimg || { msg "$rename_prog_sdcard_kernelimg_fail" ; sleep 3 ; }
+	rename_prog_sdcard_kernel || { msg "$rename_prog_sdcard_kernel_fail" ; sleep 3 ; }
 	import_prog_config_file || return 1
 
-	detect_device_model || return 1
+	detect_camera_model || return 1
 	display_info
 	
 	[[ "$dry_run" == "yes" ]] && msg "$dry_run_yes" || msg "$dry_run_no" && msg
@@ -313,13 +314,13 @@ function main() {
 		msg "$enable_custom_script_no"
 	fi
 
-	#---------- New SD card kernel image ----------
+	#---------- New SD card kernel ----------
 	msg
-	if [[ "$copy_new_sdcard_kernelimg" == "yes" ]]; then
-		msg "$copy_new_sdcard_kernelimg_no"
-		source /action_copy_new_sdcard_kernelimg.sh && msg "$copy_new_sdcard_kernelimg_succeed" || { msg "$copy_new_sdcard_kernelimg_fail" ; return 1 ; }
+	if [[ "$copy_new_sdcard_kernel" == "yes" ]]; then
+		msg "$copy_new_sdcard_kernel_no"
+		source /action_copy_new_sdcard_kernel.sh && msg "$copy_new_sdcard_kernel_succeed" || { msg "$copy_new_sdcard_kernel_fail" ; return 1 ; }
 	else
-		msg "$copy_new_sdcard_kernelimg_no"
+		msg "$copy_new_sdcard_kernel_no"
 	fi
 }
 
